blog/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from . import views
from .views import IndexView, UserControlView, WriteBlogView, UserView, BlogView, DeleteCommentView

app_name = 'blog'
urlpatterns = [

    url(r'index', IndexView.as_view(), name='index'),

    url(r'^user/(?P<slug>\w+)$', UserControlView.as_view(), name='usercontrol'),

    url(r'^(?P<u_id>[0-9]+)/(?P<slug>\w+)$', UserView.as_view(), name='user'),

    url(r'^blog/write', WriteBlogView.as_view(), name='writeblog'),

    url(r'^blog/(?P<b_id>[0-9]+)/(?P<slug>\w+)$', BlogView.as_view(), name='blog'),

    url(r'^comment/(?P<c_id>[0-9]+)/delete', DeleteCommentView.as_view(), name='comment'),
]

blog/models.py
import datetime
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User, AbstractUser
from django.utils import timezone


GENDER = (
    ('0', u'Male'),
    ('1', u'Female')
)


DEFAULT_PROFILE_PHOTO = 'static/blog/profile/default.jpg'


def user_directory_path(instance, filename):
    date = timezone.now().time()
    return 'static/blog/profile/{0}/{1}.jpg'.format(instance.id, date)


def music_directory_path(instance, filename):
    return 'static/blog/music/{0}'.format(filename)


class User(AbstractUser):
    gender = models.CharField(max_length=1, default='0', choices=GENDER)
    follow = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        through='Relationship',
        through_fields=('from_user', 'to_user')
    )
    profile_photo = models.ImageField(
        upload_to=user_directory_path,
        default=DEFAULT_PROFILE_PHOTO,
        blank=True
    )

    class Meta:
        ordering = ['date_joined']


class Relationship(models.Model):
    from_user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='from_user'
    )
    to_user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='to_user'
    )
    reviewed = models.BooleanField(default=False)
    add_date = models.DateTimeField('Date added.')


class Music(models.Model):
    singer = models.CharField(max_length=50, null=True)
    song_name = models.CharField(max_length=100, null=True)
    music = models.FileField(
        upload_to=music_directory_path,
        null=True
    )


class Blog(models.Model):
    blog_title = models.CharField(max_length=100)
    blog_content = models.TextField(blank=True, null=True)
    blog_postdate = models.DateTimeField("Date posted")
    blog_private = models.BooleanField(default=False)
    popularity = models.IntegerField(default=0)
    liked_user = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name="liked_user"
    )
    blog_author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="blog_author"
    )
    fwd_blog = models.ForeignKey(
        'self',
        on_delete=models.CASCADE,
        related_name="forward_blog",
        null=True
    )
    relate_music = models.ForeignKey(
        Music,
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )

    class Meta:
        ordering = ['-blog_postdate']

    def __str__(self):
        return "Title: " + self.blog_title + "; Author: " + User.objects.get(pk=self.blog_author_id).__str__()


class Comment(models.Model):
    """docstring for Comment"""
    comment_author = models.ForeignKey(User, on_delete=models.CASCADE)
    comment_blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    comment_content = models.TextField(blank=True, null=False)
    comment_date = models.DateTimeField("Date commented.", auto_now_add=True)

    class Meta:
        ordering = ['-comment_date']

    def __str__(self):
        return "User: " + User.objects.get(
            pk=self.comment_author_id).user_name + "; " + "Comment on blog: " + Blog.objects.get(
            pk=self.comment_blog_id).blog_title + "."

blog/forms.py
from django import forms
from newp.settings import MAX_IMAGE_SIZE, MAX_MUSIC_SIZE


IS_PRIVATE = [
    (True, True),
    (False, False)
]

MUSIC_TYPE = [
    'mp3'
]


class LoginForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(max_length=32, widget=forms.PasswordInput)


class RegisterForm(forms.Form):
    username = forms.CharField(max_length=150)
    firstname = forms.CharField(max_length=30)
    lastname = forms.CharField(max_length=30)
    email = forms.EmailField(max_length=254)
    password = forms.CharField(max_length=32, widget=forms.PasswordInput)


class ImageUploadForm(forms.Form):
    profile = forms.ImageField()

    def clean_file(self):
        file = self.cleaned_data['profile']
        if file._size > MAX_IMAGE_SIZE:
            return False
        else:
            return True


class MusicUploadForm(forms.Form):
    music = forms.FileField()

    def clean_file(self):
        file = self.cleaned_data['music']

        file_type = file.content_type.spilt('.')[1]

        if file_type in MUSIC_TYPE:
            if file._size > MAX_MUSIC_SIZE:
                return False
            else:
                return True
        else:
            return False


class BlogForm(forms.Form):
    title = forms.CharField(max_length=100)
    content = forms.CharField(widget=forms.Textarea)
    private = forms.ChoiceField(choices=IS_PRIVATE)
    music = forms.FileField()

    def clean_file(self):
        file = self.cleaned_data['music']
        info = file.content_type.split('/')
        file_type = info[1]

        if file_type in MUSIC_TYPE:
            if file._size > MAX_MUSIC_SIZE:
                return False
            else:
                return True
        else:
            return False


class ForwardForm(forms.Form):
    fwdcontent = forms.CharField(max_length=100)
    fwdprivate = forms.CharField()


class CommentForm(forms.Form):
    author_id = forms.CharField()
    content = forms.CharField(widget=forms.Textarea)

blog/views.py
from django.db.models import F
from django.shortcuts import render, get_object_or_404, Http404
from django.http import HttpResponseRedirect
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.views.generic import View, ListView
from django.views.generic.edit import ContextMixin
from django.core.exceptions import PermissionDenied

from .models import Blog, Comment, User, Music, Relationship
from .forms import CommentForm, BlogForm, ForwardForm, LoginForm, RegisterForm, ImageUploadForm, MusicUploadForm


# Create your views here.
def get_music_information(music):
    information = music.content_type.split('-')
    return information


class BaseMixin(ContextMixin):
    def get_context_data(self, **kwargs):
        context = super(BaseMixin, self).get_context_data(**kwargs)

        if self.request.user.is_active:
            user = User.objects.get(pk=self.request.user.id)
            context['log_user'] = user
        else:
            context['log_user'] = None

        context['popularity'] = Blog.objects.filter(blog_private=False).order_by('-popularity', '-id')[0:5]

        return context


class IndexView(BaseMixin, ListView):
    template_name = 'blog/index.html'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        blog = Blog.objects.none()

        if self.request.user.is_active:
            user = context['log_user']
            context['follow_list'] = user.follow.all()

            for user in user.follow.all():
                blog = blog | Blog.objects.filter(blog_author=user, blog_private=False)

        context['blog_list'] = blog
        return context

    def get_queryset(self):
        return User.objects.all()


class UserControlView(BaseMixin, View):
    def get(self, *args, **kwargs):
        slug = self.kwargs.get('slug')

        if slug == 'register':
            return render(self.request, 'blog/register.html')
        elif slug == 'manage':
            context = super(UserControlView, self).get_context_data(**kwargs)

            return render(self.request, 'blog/upload_profile.html', context)

        raise PermissionDenied

    def post(self, *args, **kwargs):
        slug = self.kwargs.get('slug')

        if slug == 'login':
            return self.login()
        elif slug == 'logout':
            return self.logout()
        elif slug == 'register':
            return self.register()
        elif slug == 'search':
            return self.search()
        elif slug == 'manage':
            return self.manage()

        raise PermissionDenied

    def login(self):
        form = LoginForm(self.request.POST)

        if form.is_valid():
            name = form.cleaned_data['username']
            pwd = form.cleaned_data['password']
            user = authenticate(username=name, password=pwd)

            if user is not None:
                self.request.session.set_expiry(0)
                login(self.request, user)

        return HttpResponseRedirect(reverse('blog:index'))

    def logout(self):
        logout(self.request)
        user_list = User.objects.order_by('date_joined')
        context = {
            'user_list': user_list,
        }

        return HttpResponseRedirect(reverse('blog:index'))

    def register(self):
        form = RegisterForm(self.request.POST)

        if form.is_valid():
            user_name = form.cleaned_data['username']
            firstname = form.cleaned_data['firstname']
            lastname = form.cleaned_data['lastname']
            pwd = form.cleaned_data['password']
            e_mail = form.cleaned_data['email']
            user = User.objects.create(username=user_name, first_name=firstname, last_name=lastname, email=e_mail)
            user.set_password(pwd)
            try:
                user.save()
                user = authenticate(username=user_name, password=pwd)
                login(self.request, user)
            except Exception:
                return render(self.request, 'blog/register.html')
            else:
                pass

        return HttpResponseRedirect(reverse('blog:index'))

    def manage(self):
        form = ImageUploadForm(self.request.POST, self.request.FILES)
        context = dict()

        if form.is_valid():
            if form.clean_file():
                log_user = User.objects.get(pk=self.request.user.id)
                log_user.profile_photo = form.cleaned_data['profile']
                log_user.save()
            else:
                context['error_message'] = 'Image too large'
                return render(self.request, 'blog/upload_profile.html', context)
        else:
            context['error_message'] = 'Submit file is nor an image.'
            return render(self.request, 'blog/upload_profile.html', context)

        return HttpResponseRedirect(reverse('blog:index'))

    def search(self):
        context = self.get_context_data()
        keyword = self.request.POST['keyword']
        blog = Blog.objects.filter(blog_title__contains=keyword, blog_private=False)
        user = User.objects.filter(username__contains=keyword)

        context['result_blog'] = blog
        context['result_user'] = user

        return render(self.request, 'blog/searchresult.html', context)


class UserView(BaseMixin, View):
    def get(self, *args, **kwargs):
        slug = self.kwargs.get('slug')

        if slug == 'homepage':
            return self.homepage()
        else:
            return Http404

    def post(self, *args, **kwargs):
        slug = self.kwargs.get('slug')

        if slug == 'follow':
            return self.follow()
        else:
            raise PermissionDenied

    def get_context_data(self, **kwargs):
        context = super(UserView, self).get_context_data(**kwargs)
        log_user = context['log_user']
        home_id = self.kwargs.get('u_id')
        user = get_object_or_404(User, pk=home_id)
        blog_list = Blog.objects.filter(blog_author=user)

        if type(log_user) is User:
            context['follow'] = user in log_user.follow.all()

            if home_id == str(log_user.id):
                is_self = True
            else:
                is_self = False
                blog_list = blog_list.filter(blog_private=False)
                try:
                    context['follow'] = user in log_user.follow.all()
                except AttributeError:
                    context['follow'] = False

        else:
            is_self = False
            context['follow'] = False
            blog_list = blog_list.filter(blog_private=False)

        context['User'] = user
        context['Blog_list'] = blog_list
        context['self'] = is_self

        return context

    def homepage(self):
        context = self.get_context_data()

        return render(self.request, 'blog/personalhomepage.html', context)

    def follow(self):
        context = self.get_context_data()
        added_user = context['User']
        log_user = context['log_user']

        if type(log_user) is User:
            if not context['follow']:
                relationship = Relationship.objects.create(
                    from_user=log_user,
                    to_user=added_user,
                    add_date=timezone.now()
                )
                relationship.save()
                context['follow'] = True
            else:
                Relationship.objects.filter(from_user=log_user, to_user=added_user).delete()
                context['follow'] = False

        return HttpResponseRedirect(reverse('blog:user', kwargs={'u_id': added_user.id, 'slug': 'homepage'}))


class WriteBlogView(BaseMixin, View):
    def get_context_data(self, **kwargs):
        context = super(WriteBlogView, self).get_context_data(**kwargs)

        return context

    def get(self, *args, **kwargs):
        form = BlogForm()
        context = self.get_context_data()
        context['form'] = form

        return render(self.request, 'blog/blog_form.html', context)

    def post(self, *args, **kwargs):
        form = BlogForm(self.request.POST, self.request.FILES)
        context = self.get_context_data()

        if form.is_valid():
            if form.clean_file():
                title = form.cleaned_data['title']
                content = form.cleaned_data['content']
                private = form.cleaned_data['private']
                music = form.cleaned_data['music']
                m = Music.objects.create()
                m.music = music
                m.save()
                post_date = timezone.now()
                author = self.request.user.id
                blog = Blog.objects.create(blog_title=title, blog_content=content, blog_postdate=post_date,
                                           blog_author_id=author, blog_private=private)
                blog.relate_music = m
                try:
                    blog.save()
                except Exception:
                    return render(reverse('blog:writeblog'))
                else:
                    return HttpResponseRedirect(reverse('blog:blog', kwargs={'b_id': blog.id, 'slug': 'view'}))
            else:
                context['error_message'] = 'Music file too large.'
                return HttpResponseRedirect(reverse('blog:writeblog'))
        else:
            return HttpResponseRedirect(reverse('blog:writeblog'))


class BlogView(BaseMixin, View):
    def get(self, *args, **kwargs):
        slug = self.kwargs.get('slug')
        if slug == 'view':
            return self.view()

    def post(self, *args, **kwargs):
        slug = self.kwargs.get('slug')

        if slug == 'delete':
            return self.deleteblog()
        elif slug == 'like':
            return self.like()
        elif slug == 'forward':
            return self.forward()
        elif slug == 'comment':
            return self.comment()

blog/templates/blog/index.html
{% extends "./base.html" %}

{% block title %}Index{% endblock %}

{% block content %}

    <div class="container">
                                    <nav class="navbar navbar-default" role="navigation">
                <div class="navbar-header">
                     <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button> <a class="navbar-brand" href="#">Index</a>
                </div>
            </nav> 

                            <div class="row clearfix">


        <div class="col-md-3 column" >
            {% if log_user %}
        
<table>
  <tbody>
    <tr>
      <td>
                          <div class="cell3">
                          <table>
  <thead>
    <tr>
      <th>
      <h1>User<h1>
      </th><th><h3>{{ user.username }}</h3>

                         </th>
    </tr>
    </thead><tbody>
    <tr><td>
       <p>Following</p>
    </td><td><p>Followers<p></td>
    </tr>
    <tr><td>
       <p><a href="{% url 'blog:usercontrol' 'following' %}">{{ following_count }}</a></p>
    </td><td><p><a href="{% url 'blog:usercontrol' 'follower' %}">{{ follower_count }}</a><p></td>
    </tr>
    </tbody></table>
                        </div><br>
      </td>
    </tr>
        {% else %}
        <tr><td>
            <div class="cell3">  <table><thead>
    <tr>
      <th>
      <h1>User<h1>
      </th><th><h3>No user.</h3>

                         </th>
    </tr>
    </thead><tbody>
    </tbody></table>
        </div><br>
        </td></tr>
    {% endif %}
    {% if follow_list %}
    <tr><td>
    <div class="cell3"><table class="table table-bordered">
  <thead>
    <tr>
      <th><h1>Following users</h1>
                         </th>
    </tr>
    </thead>
    <tbody><tr><td>
    {% for user in follow_list %}
                                        
        <a href="{% url 'blog:user' user.id 'homepage' %}" >{{ user.username }}</a><br><br>               
              {% endfor %}
              </td></tr></tbody></table>
    
                        </div></td></tr>

    {% else %}
    <tr><td>
    <div class="cell3">
    <table class="table table-bordered">
  <thead>
    <tr>
      <th>
                        <h1>Following users</h1> </th>
    </tr>
    </thead><tbody><tr><td><h3>Not following any user yet.</h3></td></tr></tbody></table>
    
        </div>

    {% endif %}
    </td></tr>
  </tbody>
</table>     
<br>
          </div> 
        <div class="col-md-6 column" >
        <table>
    {% if blog_list %}<tbody>
        <tr>
        <td>
            
            <div class="cell3">
            <table class="table table-bordered">
  <thead>
    <tr>
      <th><h1>Following blogs</h1>
                         </th>
    </tr>
    </thead><tbody>{% for blog in blog_list %}<tr><td>                        <nav class="navbar navbar-inverse" role="navigation">
                <div class="navbar-header">
                     <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button> <a class="navbar-brand" href="#">Title:</a>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li class="active">
                             <a href="{% url 'blog:blog' blog.id 'view' %}">{{ blog.blog_title }}</a>
                        </li>
                        <li class ="pull-right"><a>{{ blog.blog_postdate }}</a></li>
                    </ul>
                </div>
                       <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  
                </div>

            </nav>
                <p> {{ blog.blog_content }}</p>
      
    </td></tr>{% endfor %}</tbody></table> 
            </td></tr></tbody>
    {% else %}
     <tr>
        <td>
                   <div class="cell3">
                   <table class="table table-bordered">
  <thead>
    <tr>
      <th><h1>Following blogs</h1>
                         </th>
    </tr>
    </thead><tbody><tr><td><h3>No blog to show.</h3></td></tr></tbody></table>
                    
        
        </td></tr>
    {% endif %}
        </div>
            <div class="col-md-6 column">        <table> </table> 
    </div>
                <div class="col-md-3 column">        <table>
            <tbody>
        <tr>
        <td>
                                        <div class="cell3">
                                        <table class="table table-bordered">
  <thead>
    <tr>
      <th><h1>Hot Blog</h1>
                         </th>
    </tr>
    </thead><tbody>
        {% if popularity %}<tr><td>
        
            {% for blog in popularity %}
                {% if blog.fwd_blog %}
                     <a href="{% url 'blog:blog' blog.id 'view' %}">{{ forloop.counter }}. Forward: {{ blog.blog_title }}</a>
                     <a href="{% url 'blog:blog' blog.fwd_blog.id 'view' %}">
                        {{ blog.fwd_blog.blog_title }}</a></p>
                    <p>Popularity: {{ blog.popularity }}</p>
                {% else %}
                     <a href="{% url 'blog:blog' blog.id 'view' %}">{{ forloop.counter }}. {{ blog.blog_title }}</a>
                     <p>Popularity: {{ blog.popularity }}</p>
                {% endif %}
            {% endfor %}
        
        <br></td></tr>
    {% endif %}
    </tbody></table>

                  </div>
  </td>
  </tr>              </tbody> </table> 
    </div>
    </div>
    </div>

{% endblock %}

blog/templates/blog/viewblog.html
{% extends "./base.html" %}

{% block title %}View Blog{% endblock %}

{% block content %}
<div class="container">

                <nav class="navbar navbar-default" role="navigation">
                <div class="navbar-header">
                     <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button> <a class="navbar-brand" href="#">Title:</a>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li>
                             <a href="{% url 'blog:blog' blog.id 'view' %}">{{ blog.blog_title }}</a>
                        </li>

                                              <li class="active col-md-3 pull-right">
                                {% if self %}
                            <form action="{% url 'blog:blog' blog.id 'delete' %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-primary btn-lg">Delete</button>
                            </form>
    {% endif %}
                        </li> 
                    </ul>
                </div>
                       <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  
                </div>

            </nav>

<div class="row clearfix">
        <div class="col-md-9 column" >
        <div class="cell3">
           <table class="table">
                        <tbody>
    {% if not blog.fwd_blog %}

                        <nav class="navbar navbar-inverse" role="navigation">
                <div class="navbar-header">
                     <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button> <a class="navbar-brand" href="#">Author:</a>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li class="active">
                             <a href="{% url 'blog:blog' blog.id 'view' %}">{{ blog.blog_author.username }}</a>
                        </li>
                                              <li class="active">
                                                  {% if request.user %}
        <form action="{% url 'blog:blog' blog.id 'like' %}" method="post">
            <button type="submit" class="btn btn-success btn-lg">
                {% csrf_token %}
                {% if liked %}
                    Liked
                {% else %}
                    Like
                {% endif %}
                ({{ blog.like_count }})
            </button>
        </form>
        <br>
    {% endif %}

                        </li> 
                        <li class ="pull-right"><a>{{ blog.blog_postdate }}</a></li>
                    </ul>
                </div>
                       <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  
                </div>

            </nav>

    <tr><td>
        <h3>Content: <br></h3><p>{{ blog.blog_content }}</p></td></tr>
    {% else %}                        <nav class="navbar navbar-inverse" role="navigation">
                <div class="navbar-header">
                     <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button> <a class="navbar-brand" href="#">Author:</a>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li class="active">
                             <a href="{% url 'blog:blog' blog.id 'view' %}">{{ blog.fwd_blog.blog_author.username }}</a>
                        </li>
                                              <li class="active">
                                                  {% if request.user %}
        <form action="{% url 'blog:blog' blog.id 'like' %}" method="post">
            <button type="submit" class="btn btn-success btn-lg">
                {% csrf_token %}
                {% if liked %}
                    Liked
                {% else %}
                    Like
                {% endif %}
                ({{ blog.like_count }})
            </button>
        </form>
        <br>
    {% endif %}

                        </li> 
                        <li class ="active pull-right"><a>{{ blog.fwd_blog.blog_postdate }}</a></li>
                    </ul>
                </div>
                       <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  
                </div>

            </nav>
            <tr><td>
        <h3>Forward comment:{{ blog.blog_title }}</h3><br>
        <h3>Forward date: {{ blog.blog_postdate }}</h3><br>
        <h3></h3></td></tr><tr><td>
        <p>{{ blog.fwd_blog.blog_content }}</p></td></tr>
    {% endif %}

    {% if music %}<tr><td>
        <h3>Music:</h3><audio src="/{{ music }}" controls="controls"></audio></td></tr>
    {% endif %}
<tr><td>
    <form action="{% url 'blog:blog' blog.id 'forward' %}" method="post">
        {% csrf_token %}
        <h3>Forward message:</h3> <input type="text" name="fwdcontent"/><br>
        Private: <input type="radio" name="fwdprivate" value=1>True</input>
        <input type="radio" name="fwdprivate" value=0>False</input><br>
        <button type="submit" class="btn btn-default">Forward</button>
    </form></td></tr>
        


        <div class="cell3"><tr><td>

{% block comment %}

        {% if comment_error %}
            <h3>{{ comment_error }}</h3>
        {% endif %}
        <form action="{% url 'blog:blog' blog.id 'comment' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="comment_author_id" value="{{ request.user.id }}"/>
            <h3>Comment:</h3>
            <input type="text" name="content"/>
            <input type="submit" name="Submit"/>
        </form>

    {% endblock %}</td></tr><tr><td>

    {% block commentindex %}

        <h3>Comments ({{ blog.comment_count }}):</h3>

        {% for comment in comment_list %}

        <nav class="navbar navbar-inverse" role="navigation">
                <div class="navbar-header">
                     <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button> <a class="navbar-brand" href="#">Author:</a>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li class="active">
                             <a href="{% url 'blog:blog' blog.id 'view' %}">{{ comment.comment_author.username }}</a>
                        </li>
                                              <li class="active">
 {% if self %}
                        <form action="{% url 'blog:comment' comment.id %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-primary btn-lg">Delete</button>
                        </form>
                    {% endif %}

                        </li> 
                        <li class ="pull-right"><a>{{ comment.comment_date }}</a></li>
                    </ul>
                </div>
                       <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  
                </div>

            </nav>
                    
                
                <P>{{ comment.comment_content }}</P>
            {% endfor %}
        
    {% endblock %}</td></tr><tr><td>
    <a href="{% url 'blog:user' blog.blog_author_id 'homepage' %}">Back</a>
    </div><br></td></tr>
    </tbody></table>
    </div>
    </div>
                <div class="col-md-3 column">        <table>
            <tbody>
        <tr>
        <td>
                                        <div class="cell3">
                                        <table class="table table-bordered">
  <thead>
    <tr>
      <th><h1>Hot Blog</h1>
                         </th>
    </tr>
    </thead><tbody>
        {% if popularity %}<tr><td>
        
            {% for blog in popularity %}
                {% if blog.fwd_blog %}
                     <a href="{% url 'blog:blog' blog.id 'view' %}">{{ forloop.counter }}. Forward: {{ blog.blog_title }}</a>
                     <a href="{% url 'blog:blog' blog.fwd_blog.id 'view' %}">
                        {{ blog.fwd_blog.blog_title }}</a></p>
                    <p>Popularity: {{ blog.popularity }}</p>
                {% else %}
                     <a href="{% url 'blog:blog' blog.id 'view' %}">{{ forloop.counter }}. {{ blog.blog_title }}</a>
                     <p>Popularity: {{ blog.popularity }}</p>
                {% endif %}
            {% endfor %}
        
        <br></td></tr>
    {% endif %}
    </tbody></table>

                  </div>
  </td>
  </tr>              </tbody> </table> 
    </div>
    </div>
</div>
{% endblock %}